apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - job.yaml
  - rbac.yaml


configMapGenerator:
  - name: init-script
    files:
      - files/vault-init.py


generatorOptions:
  disableNameSuffixHash: true
