# based on https://github.com/hashicorp/vault-helm/blob/v0.29.1/values.openshift.yaml
global:
  openshift: true

injector:
  image:
    repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
    tag: "1.5.0-ubi"

  agentImage:
    repository: "registry.connect.redhat.com/hashicorp/vault"
    tag: "1.18.1-ubi"

server:
  image:
    repository: "registry.connect.redhat.com/hashicorp/vault"
    tag: "1.18.1-ubi"

  readinessProbe:
    path: "/v1/sys/health?uninitcode=204"

  dataStorage:
      enabled: true
      size: 10Gi
      storageClass: managed-nfs-storage

  route:
    enabled: true
    host: vault.apps.epyc.cloud.a-it.dev
    # annotations:
    #   kubernetes.io/tls-acme: "true"
    tls:
      termination: edge   #default: passthrough

ui:
  enabled: true

serverTelemetry:
  serviceMonitor:
    enabled: true
  prometheusRules:
    enabled: true

csi:
  # True if you want to install a secrets-store-csi-driver-provider-vault daemonset.
  #
  # Requires installing the secrets-store-csi-driver separately, see:
  # https://github.com/kubernetes-sigs/secrets-store-csi-driver#install-the-secrets-store-csi-driver
  #
  # With the driver and provider installed, you can mount Vault secrets into volumes
  # similar to the Vault Agent injector, and you can also sync those secrets into
  # Kubernetes secrets.
  enabled: false