apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

generatorOptions:
  disableNameSuffixHash: false

helmGlobals:
  chartHome: charts

helmCharts:
- name: vault
  version: 0.29.1
  releaseName: vault
  # valuesFile: values/common/common.yaml
  additionalValuesFiles:
    - values-openshift.yaml
    # - values-ha.yaml  # include to run a 3-node HA cluster


resources: []